// SandustryMP localization tables and translator.
(() => {
	"use strict";
	window.SandustryMPLocalisation = {
		create(author) {
			const AUTHOR = author;
			// ------------------------------------------------------------------
			// i18n — English by default, Polish auto-detected
			// ------------------------------------------------------------------
			const LANG = (() => {
				try {
					const langs = window.electron && window.electron.getPreferredSystemLanguagesSync ? window.electron.getPreferredSystemLanguagesSync() : [];
					const preferredLanguage = (langs[0] || navigator.language || "en").toLowerCase();
					if (preferredLanguage.startsWith("zh")) return "zh";
					if (preferredLanguage.startsWith("pl")) return "pl";
					return "en";
				} catch (e) { return "en"; }
			})();
			const STRINGS = {
				en: {
					offline: "offline", btn_host: "Host (Steam)", btn_invite: "Invite", btn_host_lan: "Host Direct",
					btn_join_lan: "Join Direct", btn_connect: "Connect", btn_start_host: "Host", btn_stop: "Stop", btn_send_world: "Send world", btn_resync: "Resync",
					host_paused: "Host paused (menu) — world frozen, will resume automatically", sync_stalled: "No world data from host for {0}s…",
					reconnecting: "Connection lost — reconnecting (attempt {0}/5)…",
					left_to_menu: "Left the co-op session (returned to title screen)",
					chat_ph: "chat message…", chat_me: "You",
					btn_join_id: "Join by ID (clipboard)", lobby_copied: "Copied!",
					clipboard_no_id: "Clipboard has no Lobby ID — first click the host's green Lobby ID line to copy it",
					hint: "click header to hide (Ctrl+Shift+H)", by: "by " + AUTHOR,
					hosting_steam: "HOSTING (Steam) — invite your friend!", hosting_lan: (p) => "HOSTING DIRECT — port " + p,
					hosting_direct_online: (a, p) => "HOSTING DIRECT — online at " + (a || "public address") + ":" + p + " (UPnP; click to hide)",
					hosting_direct_online_hidden: (p) => "HOSTING DIRECT — online on port " + p + " (UPnP; click to reveal address)",
					hosting_direct_local: (p) => "HOSTING DIRECT — port " + p + " (UPnP unavailable; LAN/VPN only)",
					joined: (tr) => "CONNECTED to host (" + tr + ")", players: (n) => "Players online: " + n,
					player_left: (n) => "Player left. Online: " + n, error: (m) => "Error: " + m,
					creating_lobby: "creating lobby...", connect_first: "Connect first!",
					no_saves: "No saves — save your game first", exporting: (n) => "Exporting world '" + n + "'...",
					export_err: (m) => "Export error: " + m, import_err: (m) => "Import error: " + m,
					decode_err: (m) => "World decode error: " + m,
					world_sent: (kb, ch) => "World sent (" + kb + " KB, " + ch + " parts)",
					world_imported: (n) => "World '" + n + "' imported! Load it: menu → Load Game",
					world_imported_loaded: (n) => "Joined host's world '" + n + "' — you're in!",
					waiting_host_world: "Connected — waiting for host to enter a world (it'll load automatically)...",
					receiving: (a, b) => "Receiving world: " + a + "/" + b,
					other_world: "⚠ NOT on host's world! Host: click 'Send world'. You: menu → Load Game → load the received save.",
					dims_differ: (a, b) => "⚠ Different world size (" + a + " vs host " + b + ") — load the host's save via Load Game.",
					sync_up: (kb, ch, q) => "upload: " + kb + " KB/s, " + ch + " chunk/s, queue " + q,
					sync_down: (kb, ch, q) => "host mirror: " + kb + " KB/s, " + ch + " chunk/s" + (q > 0 ? " — " + q + " chunks left" : ""),
					loading_world: "Loading the host's world... (a big map can take a few minutes — the game may look frozen)",
					join_prompt: "Host address (ip or ip:port):",
					ver_mismatch: "MOD VERSION MISMATCH — both players must update SandustryMP!",
					waiting_world: "Connected. Waiting for host's world — HOST must click 'Send world', then you: menu → Load Game.",
					unsupported: "⚠ Unsupported game version — the game updated and broke the mod. Re-run install, or check the Workshop page for an update.",
					mp_btn: "Multiplayer",
					lb_title: "MULTIPLAYER", lb_sub: "SandustryMP co-op — up to 4 players",
					lb_host_steam_d: "Play over the internet — invite friends from your Steam friend list",
					lb_host_lan_d: "Host directly by address; UPnP enables online connections when supported",
					lb_join_lan_d: "Connect directly to a host by address",
					lb_port: "Port",
					lb_join_id_d: "Join with a Lobby ID copied to the clipboard",
					lb_close: "✕", lb_disconnect: "Disconnect", lb_players: "Players", lb_you: "you",
					lb_id: "Lobby ID", lb_copy: "copy", lb_copied: "copied!", lb_invite: "Invite a friend",
					lb_play_last: "▶ Load last save & PLAY",
					lb_play_note: "Your world is sent to joined players automatically. You can also just use Continue / Load Game.",
					lb_wait_host: "Waiting for the host's world — it downloads and loads automatically.",
					lb_hint: "Tip: a Steam invite can be accepted at ANY time — everything else happens automatically.",
					lb_steps: "1) Invite friends   2) Hit PLAY — they will join your map automatically",
					badge_offline: "○ OFFLINE — not connected",
					badge_host: (tr) => "● HOSTING (" + tr + ")",
					badge_client: (tr) => "● CONNECTED (" + tr + ") — you are a player",
					chat_joined: (n) => n + " joined",
					chat_left: (n) => n + " left",
					lb_nick: "Your nick",
					lb_pick_save: "📂 Choose a save...", lb_pick_save_d: "load a specific world instead of the last one",
					lb_new_note: "New map? Close this window and click New Game — hosting stays active, the world is sent to players when you enter it.",
					host_enter_world_first: "Enter your world first (Continue / Load Game) — it will be sent to players automatically.",
				},
				pl: {
					offline: "offline", btn_host: "Host (Steam)", btn_invite: "Zaproś", btn_host_lan: "Host bezpośredni",
					btn_join_lan: "Dołącz bezpośrednio", btn_connect: "Połącz", btn_start_host: "Hostuj", btn_stop: "Stop", btn_send_world: "Wyślij świat", btn_resync: "Resync",
					host_paused: "Host w pauzie (menu) — świat zamrożony, wznowi się sam", sync_stalled: "Brak danych świata od hosta od {0}s…",
					reconnecting: "Zerwane połączenie — łączę ponownie (próba {0}/5)…",
					left_to_menu: "Opuszczono sesję co-op (powrót do menu głównego)",
					chat_ph: "wiadomość czatu…", chat_me: "Ty",
					btn_join_id: "Dołącz po ID (schowek)", lobby_copied: "Skopiowano!",
					clipboard_no_id: "Schowek nie zawiera Lobby ID — najpierw kliknij zieloną linię Lobby ID u hosta, żeby je skopiować",
					hint: "kliknij nagłówek by ukryć (Ctrl+Shift+H)", by: "autor: " + AUTHOR,
					hosting_steam: "HOST (Steam) — zaproś znajomego!", hosting_lan: (p) => "HOST BEZPOŚREDNI — port " + p,
					hosting_direct_online: (a, p) => "HOST BEZPOŚREDNI — online pod " + (a || "adresem publicznym") + ":" + p + " (UPnP; kliknij, aby ukryć)",
					hosting_direct_online_hidden: (p) => "HOST BEZPOŚREDNI — online na porcie " + p + " (UPnP; kliknij, aby pokazać adres)",
					hosting_direct_local: (p) => "HOST BEZPOŚREDNI — port " + p + " (UPnP niedostępne; tylko LAN/VPN)",
					joined: (tr) => "POŁĄCZONO z hostem (" + tr + ")", players: (n) => "Gracze online: " + n,
					player_left: (n) => "Gracz wyszedł. Online: " + n, error: (m) => "Błąd: " + m,
					creating_lobby: "tworzenie lobby...", connect_first: "Najpierw połącz się!",
					no_saves: "Brak save'ów — zapisz grę najpierw", exporting: (n) => "Eksport świata '" + n + "'...",
					export_err: (m) => "Błąd eksportu: " + m, import_err: (m) => "Błąd importu: " + m,
					decode_err: (m) => "Błąd dekodowania świata: " + m,
					world_sent: (kb, ch) => "Świat wysłany (" + kb + " KB, " + ch + " części)",
					world_imported: (n) => "Świat '" + n + "' zaimportowany! Wczytaj go: menu → Load Game",
					world_imported_loaded: (n) => "Dołączono do świata hosta '" + n + "' — jesteś w grze!",
					waiting_host_world: "Połączono — czekam aż host wejdzie do świata (wczyta się automatycznie)...",
					receiving: (a, b) => "Odbieranie świata: " + a + "/" + b,
					other_world: "⚠ NIE jesteś na świecie hosta! Host: kliknij 'Wyślij świat'. Ty: menu → Load Game → wczytaj otrzymany save.",
					dims_differ: (a, b) => "⚠ Inny rozmiar świata (" + a + " vs host " + b + ") — wczytaj save hosta przez Load Game.",
					sync_up: (kb, ch, q) => "wysyłka: " + kb + " KB/s, " + ch + " chunk/s, kolejka " + q,
					sync_down: (kb, ch, q) => "lustro hosta: " + kb + " KB/s, " + ch + " chunk/s" + (q > 0 ? " — zostało " + q + " paczek" : ""),
					loading_world: "Wczytywanie świata hosta... (duża mapa może potrwać kilka minut — gra może wyglądać na zawieszoną)",
					join_prompt: "Adres hosta (ip lub ip:port):",
					ver_mismatch: "RÓŻNE WERSJE MODA — obaj gracze muszą zaktualizować SandustryMP!",
					waiting_world: "Połączono. Czekam na świat hosta — HOST musi kliknąć 'Wyślij świat', potem Ty: menu → Load Game.",
					unsupported: "⚠ Niewspierana wersja gry — gra się zaktualizowała i rozjechała moda. Uruchom install ponownie albo sprawdź update na Warsztacie.",
					mp_btn: "Multiplayer",
					lb_title: "MULTIPLAYER", lb_sub: "SandustryMP co-op — do 4 graczy",
					lb_host_steam_d: "Graj przez internet — zaproś znajomych z listy Steam",
					lb_host_lan_d: "Hostuj bezpośrednio przez adres; UPnP umożliwia grę online, gdy jest obsługiwane",
					lb_join_lan_d: "Połącz się bezpośrednio z hostem przez adres",
					lb_port: "Port",
					lb_join_id_d: "Dołącz po Lobby ID skopiowanym do schowka",
					lb_close: "✕", lb_disconnect: "Rozłącz", lb_players: "Gracze", lb_you: "ty",
					lb_id: "Lobby ID", lb_copy: "kopiuj", lb_copied: "skopiowane!", lb_invite: "Zaproś znajomego",
					lb_play_last: "▶ Wczytaj ostatni save i GRAJ",
					lb_play_note: "Twój świat wyśle się dołączonym graczom automatycznie. Możesz też po prostu użyć Kontynuuj / Wczytaj.",
					lb_wait_host: "Czekam na świat hosta — pobierze się i wczyta automatycznie.",
					lb_hint: "Tip: zaproszenie Steam możesz przyjąć w KAŻDEJ chwili — reszta dzieje się sama.",
					lb_steps: "1) Zaproś znajomych   2) Wciśnij GRAJ — dołączą na Twoją mapę automatycznie",
					badge_offline: "○ OFFLINE — nie połączono",
					badge_host: (tr) => "● HOSTUJESZ (" + tr + ")",
					badge_client: (tr) => "● POŁĄCZONY (" + tr + ") — jesteś graczem",
					chat_joined: (n) => n + " dołączył",
					chat_left: (n) => n + " wyszedł",
					lb_nick: "Twój nick",
					lb_pick_save: "📂 Wybierz save...", lb_pick_save_d: "wczytaj konkretny świat zamiast ostatniego",
					lb_new_note: "Nowa mapa? Zamknij to okno i kliknij Nowa — hosting zostaje aktywny, świat wyśle się graczom gdy do niego wejdziesz.",
					host_enter_world_first: "Najpierw wejdź do świata (Kontynuuj / Wczytaj) — graczom wyśle się automatycznie.",
				},
				zh: {
					offline: "离线", btn_host: "创建房间 (Steam)", btn_invite: "邀请", btn_host_lan: "直接创建主机",
					btn_join_lan: "直接加入", btn_connect: "连接", btn_start_host: "创建主机", btn_stop: "停止", btn_send_world: "发送世界", btn_resync: "重新同步",
					host_paused: "房主已暂停(菜单中)——世界已冻结,将自动恢复", sync_stalled: "已 {0} 秒未收到房主的世界数据…",
					reconnecting: "连接已断开——正在重新连接(第 {0}/5 次尝试)…",
					left_to_menu: "已离开合作会话(已返回主菜单)",
					chat_ph: "聊天消息…", chat_me: "你",
					btn_join_id: "通过ID加入(剪贴板)", lobby_copied: "已复制!",
					clipboard_no_id: "剪贴板中没有房间ID——请先点击房主的绿色房间ID行进行复制",
					hint: "点击标题栏隐藏 (Ctrl+Shift+H)", by: "作者:" + AUTHOR,
					hosting_steam: "正在创建房间(Steam)——邀请你的朋友吧!", hosting_lan: (p) => "正在直接创建主机——端口 " + p,
					hosting_direct_online: (a, p) => "正在直接创建主机——在线地址 " + (a || "公网地址") + ":" + p + " (UPnP；点击隐藏)",
					hosting_direct_online_hidden: (p) => "正在直接创建主机——在线端口 " + p + " (UPnP；点击显示地址)",
					hosting_direct_local: (p) => "正在直接创建主机——端口 " + p + " (UPnP不可用；仅限局域网/VPN)",
					joined: (tr) => "已连接到房主(" + tr + ")", players: (n) => "在线玩家:" + n,
					player_left: (n) => "玩家已离开。在线人数:" + n, error: (m) => "错误:" + m,
					creating_lobby: "正在创建房间...", connect_first: "请先连接!",
					no_saves: "没有存档——请先保存游戏", exporting: (n) => "正在导出世界 '" + n + "'...",
					export_err: (m) => "导出错误:" + m, import_err: (m) => "导入错误:" + m,
					decode_err: (m) => "世界解码错误:" + m,
					world_sent: (kb, ch) => "世界已发送(" + kb + " KB," + ch + " 部分)",
					world_imported: (n) => "世界 '" + n + "' 已导入!请加载它:菜单 → 加载游戏",
					world_imported_loaded: (n) => "已加入房主的世界 '" + n + "'——你已进入游戏!",
					waiting_host_world: "已连接——正在等待房主进入世界(将自动加载)...",
					receiving: (a, b) => "正在接收世界:" + a + "/" + b,
					other_world: "⚠ 你不在房主的世界中!房主:点击'发送世界'。你:菜单 → 加载游戏 → 加载收到的存档。",
					dims_differ: (a, b) => "⚠ 世界大小不同(" + a + " 对比房主的 " + b + ")——请通过加载游戏来加载房主的存档。",
					sync_up: (kb, ch, q) => "上传:" + kb + " KB/s," + ch + " 区块/s,队列 " + q,
					sync_down: (kb, ch, q) => "房主镜像:" + kb + " KB/s," + ch + " 区块/s" + (q > 0 ? " ——还剩 " + q + " 个区块" : ""),
					loading_world: "正在加载房主的世界...(大地图可能需要几分钟——游戏可能看起来像卡住了)",
					join_prompt: "房主地址(ip 或 ip:port):",
					ver_mismatch: "模组版本不匹配——双方玩家都必须更新 SandustryMP!",
					waiting_world: "已连接。正在等待房主的世界——房主需要点击'发送世界',然后你:菜单 → 加载游戏。",
					unsupported: "⚠ 不支持的游戏版本——游戏已更新并导致模组失效。请重新运行安装程序,或前往创意工坊页面查看更新。",
					mp_btn: "多人游戏",
					lb_title: "多人游戏", lb_sub: "SandustryMP 合作模式——最多4名玩家",
					lb_host_steam_d: "通过互联网游玩——从Steam好友列表邀请朋友",
					lb_host_lan_d: "通过地址直接创建主机；支持时UPnP可启用在线连接",
					lb_join_lan_d: "通过地址直接连接主机",
					lb_port: "端口",
					lb_join_id_d: "使用复制到剪贴板的房间ID加入",
					lb_close: "✕", lb_disconnect: "断开连接", lb_players: "玩家", lb_you: "你",
					lb_id: "房间ID", lb_copy: "复制", lb_copied: "已复制!", lb_invite: "邀请朋友",
					lb_play_last: "▶ 加载最新存档并开始游戏",
					lb_play_note: "你的世界会自动发送给已加入的玩家。你也可以直接使用继续/加载游戏。",
					lb_wait_host: "正在等待房主的世界——它会自动下载并加载。",
					lb_hint: "提示:Steam邀请可以在任何时候接受——其余的都会自动完成。",
					lb_steps: "1) 邀请朋友   2) 点击开始游戏——他们会自动加入你的地图",
					badge_offline: "○ 离线——未连接",
					badge_host: (tr) => "● 正在创建房间(" + tr + ")",
					badge_client: (tr) => "● 已连接(" + tr + ")——你是一名玩家",
					chat_joined: (n) => n + " 加入了",
					chat_left: (n) => n + " 离开了",
					lb_nick: "你的昵称",
					lb_pick_save: "📂 选择存档...", lb_pick_save_d: "加载指定的世界而不是最新的存档",
					lb_new_note: "新地图?关闭此窗口并点击新游戏——创建房间状态保持激活,当你进入世界后会自动发送给玩家。",
					host_enter_world_first: "请先进入你的世界(继续/加载游戏)——将自动发送给玩家。",
				},
			};
			const t = (key, ...args) => {
				const localizedValue = (STRINGS[LANG] && STRINGS[LANG][key]) || STRINGS.en[key] || key;
				return typeof localizedValue === "function" ? localizedValue(...args) : localizedValue;
			};

			return { LANG, STRINGS, t };
		}
	};
})();
